pipelines:
  custom:
    trigger_pipeline_remote_repo:
      - variables:
        - name: INFRA_REPO_NAME
        - name: INFRA_REPO_BRANCH_NAME

      - step:
          image: atlassian/default-image:3
          script:
            - BITBUCKET_OAUTH_TOKEN=$(curl -s  -X POST -u "${INFRA_PROJECT_CONSUMER_KEY}:${INFRA_PROJECT_CONSUMER_SECRET}" https://bitbucket.org/site/oauth2/access_token -d grant_type=client_credentials | jq -r '.access_token')
            - pipe: atlassian/trigger-pipeline:5.1.0
              variables:
                REPOSITORY: '$INFRA_REPO_NAME'
                REF_TYPE: 'branch'
                REF_NAME: "$INFRA_REPO_BRANCH_NAME"
                BITBUCKET_ACCESS_TOKEN: $BITBUCKET_OAUTH_TOKEN
                CUSTOM_PIPELINE_NAME: 'airflow-helm'
                WAIT: 'true'
    deploy_to_ecr:
      - step:
          oidc: true
          name: Upload Airflow Image to ECR
          image: atlassian/default-image:3
          caches:
            - docker
          script:
            # build the image
            - TAG=${BITBUCKET_COMMIT}
            - /bin/sh $BITBUCKET_CLONE_DIR/scripts/generate-project-config.sh
            - source $BITBUCKET_CLONE_DIR/project_conf.sh
            - docker build . --platform linux/amd64 -t "${IMAGE_NAME}:${BITBUCKET_COMMIT}" -f $BITBUCKET_CLONE_DIR/Dockerfile
            - BITBUCKET_OAUTH_TOKEN=$(curl -s  -X POST -u "${INFRA_PROJECT_CONSUMER_KEY}:${INFRA_PROJECT_CONSUMER_SECRET}" https://bitbucket.org/site/oauth2/access_token -d grant_type=client_credentials | jq -r '.access_token')
            # use the pipe to push the image to AWS ECR
            - pipe: atlassian/aws-ecr-push-image:2.0.0
              variables:
                AWS_DEFAULT_REGION: "${REGION}"
                AWS_OIDC_ROLE_ARN: "${AWS_BITBUCKET_PIPELINE_ROLE_ARN}"
                IMAGE_NAME: "${IMAGE_NAME}"
                TAGS: "${TAG}"

          services:
            - docker

      