product_analytics_elt_daily:
  default_args:
    owner: airflow
    start_date: "2021-01-01"
    retries: 1
    email: "{{ var.value.email_list }}"
    email_on_failure: true
    email_on_retry: false
  schedule_interval: "0 11 * * *"
  concurrency: 1
  max_active_runs: 1
  catchup: False
  tags: ["From: Postgres", "to: Redshift", "Tool: Embulk", "Tool: dbt", "Schedule: Daily", "Environment: PROD", "Type: ELT"]
  doc_md: | 
    # Product Analytics ELT Daily
    #### Extracted Database: Airflow Metastore
    #### Tools: Embulk, dbt, PostgresOperator, CustomEmbulkEcsOperator
    #### Bucket: project-s3-bucket/data/raw/airflow_monitoring
    #### Schema Redshift: raw_airflow_monitoring
    #### Additional info: Daily Airflow db extraction, the following tables are copied full refresh:
    #### dag, dag_run, task_intance and taks_fail.
    #### The product analytics extension launches a dbt run for both monitoring models. 
